version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: kryon-server
    container_name: kryon-node-server
    command: npm run start
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    networks:
      - kryon-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: kryon-client
    container_name: kryon-react-client
    command: npm run start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - kryon-network

networks:
    kryon-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local